[phases.setup]
nixPkgs = ["python3", "nodejs"]

[phases.build]
cmds = [
    "npm install --prefix frontend",
    "npm run build --prefix frontend",
    "pip install -r requirements.txt"
]

[phases.start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
